### ISSUE TITLE
The function explaining why Cinnamon Toast Crunch is good does not explain why

### ISSUE THREAD

**Issue by ghost** [towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch#11]
The function iMeanMost() does not mention why Cinnamon Toast it is 'good'. Maybe add a function explaining why Cinnamon Toast Crunch is 'good', so people are absolutely sure it is? I (sort-of) don't know either.

(maybe this can be put in the same release as the pull request I sent (if it gets merged)?)

**Comment by towerofnix** [comment]
I'm uncertain as to whether or not the essence behind Cinnamon Toast Crunch's *goodness* can even be captured, let alone in words only. It's simply a fact of life, you know? Birds fly, gravity falls, stevens universe, Cinnamon Toast Crunch is good.

On the other hand, an array of personal testimonials as to why it is good, and a function which provides one randomly, may be more in spirit. We can't declare the root reason, but lived examples may be just as compelling! What do you think?

**Comment by ghost** [comment]
> I'm uncertain as to whether or not the essence behind Cinnamon Toast Crunch's _goodness_ can even be captured, let alone in words only. **It's simply a fact of life, you know? Birds fly, gravity falls, stevens universe, Cinnamon Toast Crunch is good.**
> 
> On the other hand, an array of personal testimonials as to why it is good, and a function which provides one randomly, may be more in spirit. We can't declare the root reason, but lived examples may be just as compelling! What do you think?

Maybe a function named along the lines of whyIsItGood() could mention that its "goodness" cannot be described in words along something similar to what I have bolded?

(I know this repository is sort-of a joke)
