### ISSUE TITLE
Good example package

### ISSUE THREAD

**Issue by ajskateboarder** [towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch#13]
Better than how-to-npm which didn't even work for me :|

**Comment by towerofnix** [comment]
Dang, nice, lol.

**Comment by ajskateboarder** [comment]
It should be made a TypeScript package tbh

**Comment by towerofnix** [comment]
I'll leave that to someone who wants to publish a derivative package. It's public domain!

**Comment by ajskateboarder** [comment]
Alright :)
