### ISSUE TITLE
Um actually !:1;1;21:!!:!:!:

### ISSUE THREAD

**Issue by hueychen27** [towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch#14]
Cinnamon toast crunch unhelty ahaha so badd!!!!!!111111111111111111

**Comment by towerofnix** [comment]
Yes yes, true enough, to be certain! Indeed, though it may seem an enigma, some kids *for this very reason* [don't love the taste of cinnamon toast crunch!](https://github.com/towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch/issues/2)

Popular indication indicates it's surely [pretty tasty to most](https://github.com/towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch/blob/master/examples/stereotyping_fixed.js), though.

Yum yum yum.
