### ISSUE TITLE
getReasonWhyKidsLoveTheTasteOfCinnamonToastCrunch() should raise warning

### ISSUE THREAD

**Issue by serprinss** [towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch#7]
`getReasonWhyKidsLoveTheTasteOfCinnamonToastCrunch()` should raise warning `Don't stereotype`

**Comment by towerofnix** [comment]
Agreed. Would accept a PR! Please bump the major version too, since this would be a breaking change.

**Comment by serprinss** [comment]
should `getReasonWhyKidsLoveTheTasteOfCinnamonToastCrunch()` still return `Don't stereotype`

**Comment by towerofnix** [comment]
if it throws an error theres no reason to return anything too, nope :P
