### ISSUE TITLE
What if someone has no idea what cinnamon toast crunch is?

### ISSUE THREAD

**Issue by ghost** [towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch#9]
Not everyone might know what it is, so maybe there could be a function with a definition of what it is?

**Comment by towerofnix** [comment]
Y'know what?

Yes.

send a proposal if you like and we'll have a look :D

**Comment by ghost** [comment]
to be honest, I partially do not know what it really is either (apart from it involving cinnamon, toast and something crunchy)

**Comment by towerofnix** [comment]
Ah, should've figured that might be the case.

Published an update which should be at least a little informative! acb244e462f37435af2469a85b0cbe82d7b744e0
